### ISSUE TITLE
Name the probes

### ISSUE THREAD

**Issue by Totoleheros** [tobyweston/temperature-machine#34] opened 2017-12-01 08:59 UTC
I run a raspberry pi3 with 5 probes connected to it. Is there a way to give a name to each of them? If not, to have the possibility to it from the web interface could be nice.
Thank you again for this great project.

**Comment by tobyweston** [comment] 2017-12-01 10:51
Looks like a duplicate of #2 

I plan on having this configurable so you can map a sensor name (like 28-xxxx) to a friendly name, that work for you?

**Comment by Totoleheros** [comment] 2017-12-01 22:05
Your plan to map each sensor with a name would be ok for me, thanks!

**Closed as completed** 2017-12-13 08:40 UTC
Labels: duplicate
